name: Android CI

on:
  push:    
    branches:    
      - master
    tags: v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      env: 
        BINTRAY_KEY:${{ secrets.BINTRAY_KEY }}
      run: ./gradlew build bintaryUpload -PbintrayUser=teckjiang -PbintaryKey=$BINTRAY_KEY
